name: drag_and_drop_lists
description: A flutter package to allow drag-and-drop reordering of two-level lists.
version: 0.3.0
homepage: https://github.com/philip-brink/DragAndDropLists

environment:
  sdk: '>=3.4.1 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: